name: Test & Build

on:
  workflow_dispatch:
  push:
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'pkg/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    strategy:
      matrix:
        go: ['1.18']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Run Tests...
        run: go test -v -vet=off -race ./...
      - name: Build...
        run: go build -race cmd/main.go
      - name: Bump version and push tag dry-run
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        id: release
        uses: anothrNick/github-tag-action@1.35.0
        env:
          INITIAL_VERSION: 0.0.0
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: master
          DRY_RUN: false
          WITH_V: true
